{% set name = "azure-mgmt-rdbms" %}
{% set version = "10.2.0b17" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: d679d1932af8226efd07b0c3a86cff14eacf013a05686844f9aeebe5b64cb8e4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - isodate >=0.6.1
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2

test:
  imports:
    - azure.mgmt.rdbms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: This is the Microsoft Azure RDBMS Management Client Library.
  description: This is the Microsoft Azure RDBMS Management Client Library.
  license: MIT
  license_file: LICENSE
  license_family: MIT 
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://github.com/Azure/azure-sdk-for-python
  
